### ISSUE TITLE
System status for queued jobs is reporting incorrect number for jobs requesting GPU

### ISSUE THREAD

**Issue by ericfranz** [OSC/osc-systemstatus#80]
![screen 2020-02-19 at 1 15 38 PM](https://user-images.githubusercontent.com/512333/74862371-05378080-531a-11ea-908f-837c86147879.png)

It is possible that the 688 requesting GPU in this instance is including what moab considers "blocked jobs".

One of the issues here is that we have two different sources of information for jobs. One is eligible jobs from showq -s (for queued jobs). The other is qstat -f (i.e. ood_core's info_all).

**Comment by msquee** [comment]
Fixed by https://github.com/OSC/osc-systemstatus/pull/89
